### ISSUE TITLE
&c. - marks in alliterative verse - remove from xml comment 

### ISSUE THREAD

**Issue by pdurusau** [digitaltolkien/a-middle-english-vocabulary#2]
Dover Reprint, Abbreviations has:

allit. alliteration; (in) alliterative verse, &c.

I take that to mean "#Bryght(e)#, #Briȝt#, #Bryȝt#, #Briht# (XII), #Bryht# (XV), &c.," are all uses in alliterative verses. I don't see any reason to distinguish the final "#Bryht# (XV), &c.," from the others based on punctuation. Variations in alliterative verse?

**Comment by jtauber** [comment]
I'm not sure what the relationship is you're suggesting between the expansion of the abbreviation `allit.` and the headwords with alternate spellings.

The abbreviation `allit.` doesn't even appear in the entry for **Bryght(e)** &c. so I'm not sure how you're drawing any connection.

**Comment by pdurusau** [comment]
Sorry, I was unclear. The abbreviations section for the work lists: &c. as the abbreviation for "(In) alliterative verse". The line in question ends with "&c." which I take to mean these orthographic forms appear "in alliterative verse." My bad for using allit. as opposed to &c. I was substituting one abbreviation for another.

**Comment by jtauber** [comment]
The line

> allit. alliterative; (in) alliterative verse, &c.

under ABBREVIATIONS

just means that `allit.` is an abbreviation for "alliterative; (in) alliterative verse, etc."

**Comment by pdurusau** [comment]
My bad.
