### ISSUE TITLE
Example 3: grouping alliterative forms 

### ISSUE THREAD

**Issue by pdurusau** [digitaltolkien/a-middle-english-vocabulary#3]
Assuming I'm right about &c. marking all the forms as used in alliterative verse, then the @type attribute on <form> could be used to capture that assertion about these forms. That is: "These forms are found in alliterative verses."

Question: Do you want to discover and record all uses of these forms throughout the reader and distinguish between use in alliterative verses versus simple variants? I ask because I can't hear the distinctions (long and boring story) so while I can help with the processing, separation based on sound would require someone with that skill.

**Comment by jtauber** [comment]
`&c.` is just `etc.` It is used to end a list (of forms or citations) when incomplete.

I don't see any connection with this and which forms appear in alliterative verse.

**Comment by pdurusau** [comment]
OK, my bad. Sorry about that.
